### ISSUE TITLE
Support for schema evolution?

### ISSUE THREAD

**Issue by coryodaniel** [Strech/avrora#27]
I just started using Avrora and I was trying to evolve a schema. It looks like when I encode a record and a schema isn't present, avrora will store the schema in my registry, but if I make a change to my schema and encode a new record, it will use the original schema. Same thing if you clear the memory store.

I found that if you create a new version manually, avrora will get the correct one.

I'm not sure if I'm misusing, or if the feature doesnt exist. I'd love to help if it does not.

**Comment by Strech** [comment]
Hey @coryodaniel and thanks for the report. May I ask you to describe the process which causes an issue with step-by-step instructions that I can reproduce it?

So far I understand that you have an empty registry and encode something with `schema/v1` Avrora is registering it and encode the message, then you somehow change the schema (questions: where and how?) and Avrora is still using old `schema/v1`

May I ask you to clarify the moment of evolution of the schema?

1. Do you update the schema file? If yes, I think Avrora will not re-read it because it doesn't know that file is updated 🤔 
2. Do you update the registry schema outside Avrora? If yes, Avrora will read the new registry schema if a global-naming cache is invalidated, but not a file.

Can you elaborate on that?

**Comment by coryodaniel** [comment]
My hope was that #1 would work (it doesn’t). #2 works as expected.

I was editing the schema in priv/ and redeploying with Avrora encoding the new message payload. When consuming records it lacks any new fields In the new schema. I wonder if that’s worth logging a message that fields are being dropped?

Thanks,

Cory O’Daniel

**Comment by Strech** [comment]
Ah, got it, then it's definitely an issue, that local schema file goes after the registry, it should be first especially on startup.

I will make this scenario locally and check that it will work correctly, also will what I can do with logging of dropped fields (agree that will be great to know that they were dropped)

**Comment by coryodaniel** [comment]
Awesome, much appreciated!

**Comment by Strech** [comment]
@coryodaniel Hey, I've a PR with fix #30 I plan to release it today/tomorrow. Any feedback is appreciated (if you have one) 🤝
