### ISSUE TITLE
jsonschema support

### ISSUE THREAD

**Issue by markusfeyh** [Strech/avrora#46]
What would it take to also support jsonschema?

**Comment by Strech** [comment]
Hey @markusfeyh, thanks for a question. Do you mean by that – let's accept JSON schema as a schema source? Something like this https://github.com/thedumbterminal/jsonschema-avro?

Can I ask you to share your demand on that? I think it might help me to better understand your needs.

**Comment by markusfeyh** [comment]
> accept JSON schema as a schema source?

Yes

> Can I ask you to share your demand on that?

From working with Avro and jsonschema, the jsonschema seems more ergonomic and easier for other developers to learn. I would anticipate for this to be more popular in the future.

**Comment by Strech** [comment]
I've checked a Schema Registry and starting 5.5 it supports Avro, JSON Schema, and Protobuf. I will take a look at how is it working and what can be done for the support

**Comment by Strech** [comment]
I did a small research and I would say it would be problematic to add support for Protobuf and JSON Schema right here. The whole library is working with Avro. I think if it would be possible we could make a plugin system which will allow us to enable different libraries under the hood.

So far I will close this PR because I don't see a big need for those changes/investments. Thanks a lot for your request and sorry that I have to postpone it for a while
